### PR TITLE
Exercise

### PR DESCRIPTION
**Pull request by pushred**
@levkanter @amahon 

_Please see my emailed disclaimer before following these links:_

http://sixofone.pushred.co/posts/are-we-out-of-the-woods-yet
http://sixofone.pushred.co/posts/are-we-out-of-the-woods-yet?edit

Only tested in Chrome, looks mostly okay in Safari/FF.

---

So in our discussion last week Lev asked about my focus on static sites, I remember explaining that it's really node, not so much static sites per se. But here we have _another_ static site.

I've actually done only a few small database backed projects hands-on, so perhaps what's second nature to LAMP, Rails, Django, etc. people isn't as much for me yet. I could have done this with a normal backend, if I'd had I would have made a quick [hapi](http://hapijs.com/) server and hooked up Postgres. But given that the persistence requirement was pretty straightforward I decided to do something a little more lightweight.

This is really what I appreciate about static sites: they are portable and require no maintenance once deployed. It's also awesome that I can easily deploy them to a CDN and ensure fast access globally. I like this strategy even when a server is in play.

Things like IndexedDB, service workers, and Lambda are also really opening up a whole lot of interesting possibilities.
### Serverless Server

A talk at brooklyn.js last year put [PouchDB](https://pouchdb.com/) on my radar and that came to mind here for the database as a super quick and easy way to check that off the list. But it's only persisted locally in the browser by default, and that that's not viable beyond a prototype. So I hooked up CouchDB hosted by IBM Cloudant which reduces Pouch's role to a client. It's sync capabilities are [what's really interesting](http://www.pocketjavascript.com/blog/2015/11/23/introducing-pokedex-org) though.

As a static site it's also problematic to make new pages of course. To handle this I'm actually generating them on the fly with a Lambda function triggered on a successful callback from calls to Cloudant in the browser. This isn't very secure! Ideally Cloudant would offer a webhook API but couldn't find such a thing so in reality this would probably have to use some sort of proxy.
### JS

The requirements here were also pretty straightforward so I used (mostly) vanilla ES2015 JS. Babel still feels heavy to add to a project but there's certainly a valid argument about proactively addressing technical debt. Classes and template literals make this feel a bit React-ey to me, it's not much different from stateless functions as they are today, with no DOM optimizations. For events I borrowed Backbone's delegation approach and config style.

You may notice that I really like arrow functions! I am still concerned about their impact in debugging however — anonymous functions galore.
### CSS

That headline was a puzzle! I'm still not happy with this solution because of the wonky side effects of the inline element and negative positioning. I was committed to staying CSS-only but in reality some JS would help.

I went ahead and made the layout responsive, my general approach is like this:

**Markup → Formatting → Narrow styling → Widescreen → Behavior → Server**

The jump to a grid was just another stop along the way.
### Time

I failed! 12 hours seemed like such a long time. I burned through almost half with a distraction into srcset and building myself a tool to avoid arbitrary image breakpoints. Normally I like using [imgix](https://www.imgix.com/) for this, but I didn't want to add _too_ many third-parties into the mix. I could have used responsivebreakpoints.com and called it a day but something I like about build processes is that they document our process in code. And sometimes it's worth investing some time into a tool for use later.

CSS was also quite a speedbump. I could have stopped short somewhere but I can get a bit stubborn with seeing things through. I've kept a todo list below that I've added to as things have come to mind.

After I finished all of that the Lambda/PouchDB stuff was just a cooldown lap and I really wanted to give it a go. So perhaps look at my time invested as pretty close to 12 hours for the core of the exercise and then some extra time in me doing ancillary exploration as an investment in myself and future projects.

I tracked my time into mostly granular chunks however, here's how it went:

| notes | time |
| --- | --- |
| Markup, setup tools, research srcSet and responsive image breakpoints, start resizeImages | 3.64 |
| Finish resizeImages task, setup s3 uploads and deploy to CloudFront | 3.57 |
| Initial styling | 4.35 |
| Setup Babel/JS bundle, add unorphan | 0.75 |
| Style post layout, make responsive | 1.86 |
| Make title editable | 0.38 |
| Style fixes | 2.43 |
| Finish making title editable | 1.78 |
| Persist titles with PouchDB | 0.52 |
| Deploy pages to CloudFront | 2.06 |
| Hookup Cloudant and Lambda | 2.23 |
|  | **23.57** |
### Open Source

I actually intend to extract the resize_images code and publish it to npm at the soonest opportunity since there's not something that does this yet. This is something I forgot to discuss with you guys last week actually, I'm a big believer in open source and a general culture of sharing things like this. I try to make personal time for it but really appreciate opportunity in the workday where interests align.
## todo
- [x] make images responsive with srcset
- [x] prevent widows
- [x] deploy to cloudwatch
- [x] make header title editable
- [x] validate title content
- [x] generate slugs from titles, validate uniqueness and serialize as needed
- [x] persist titles/slugs in browser w/ PouchDB
- [x] Lost grid
- [x] tweaks at narrow breakpoint
- [ ] add grid toggle with Lost edit mode
- [x] persist titles/slugs in Cloudant via PouchDB sync
- [x] script db init, seed with posts
- [x] render + upload pages for newly titled pages with Lambda
- [x] trigger function on sync cb
- [ ] crop photo, anchor bottom for use when wider
- [ ] validate metadata
- [ ] dockerize
- [ ] extract image resizing task and test/publish

### CODE REVIEW

**Comment by LevKanter** [comment]
@pushred running into a local issue running `npm run dev`:

image

I installed globally `env-cmd` (it seems like it's not listed in the package.json) and added an env.json file, but still running into what I screenshotted.

**Comment by pushred** [comment]
Hmm it's here: https://github.com/pushred/sixofone.pushred.co/blob/exercise/package.json#L29

You'll want to make sure to use that fork which adds support for JSON files. Looks like this is failing in the image resizing library I'm using though, sharp. It's got a native extension which might be in a weird place on your machine, not sure how reliably that installs.

But it might be your node/npm version actually, see:
https://github.com/pushred/sixofone.pushred.co/blob/exercise/package.json#L17-L20

Looks like you're on 4.5.0 / 2.15.9

**Comment by pushred** [comment]
If updating there doesn't do the job you can also remove the resizeImages task and module from the gulpfile, other things _should_ work. Native extensions are a pain, but slim pickings on image resizing libs that don't require them..

**Comment by LevKanter** [comment]
ah thanks! re: node/npm versions-- just updated and getting the same thing, so will look into getting around resizeImages

**Pull request closed without merging**
